---
name: Test

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        run: bundle exec rake spec

  tests:
    if: always()
    needs:
      - test
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
